config/routes.rb
Rails.application.routes.draw do
  # RegistrationController
  root to: 'registration#index'

  get 'registration/dr_reg_page', to: 'registration#dr_reg_page', as: :dr_reg_p

  get 'registration/hst_reg_page', to: 'registration#hst_reg_page', as: :hst_reg_p

  post 'registration/dr_reg', to: 'registration#dr_reg', as: :dr_reg

  post 'registration/hst_reg', to: 'registration#hst_reg', as: :hst_reg
  ##
  ## ReyController
  post 'rey/rey_page', to: 'rey#rey_page', as: :rey_page

  get 'rey/mail_page', to: 'rey#mail_page', as: :mail_page

  post 'rey/rey_use/:myn_id', to: 'rey#rey_use', as: :rey_use
  ##
  ## StatisticController
  post 'statistic/recalculate', to: 'statistic#recalculate', as: :recalc

  get 'statistic/data_gets', to: 'statistic#data_gets', as: :stat_page

  get 'statistic/dr_success', to: 'statistic#dr_success', as: :dr_success
  ##
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/rey_controller.rb
class ReyController < ApplicationController
  def rey_page
    login = params[:rey_login]
    @log_result, @muayene_id = login_control(login)
  end

  def mail_page
    @mails = MailList.mails_get
  end

  def rey_use
    rey_form = params[:rey_cevap]
    muayene_id = params[:myn_id]
    @proc_response = ReyKayitlari.rey_kayit(rey_form, muayene_id)
  end

  private

  def login_control(param)
    tc = param[:tc].to_s != '' ? param[:tc].to_s : nil
    pass = param[:pass].to_s != '' ? param[:pass].to_i : nil

    if !(tc && pass)
      'TC kimlik numaranız veya şifreniz hatalı. Tekrar deneyiniz..'
    elsif tc.length != 11 || tc.to_i.to_s.length != 11
      'TC kimlik numaranız hatalı. Kontrol ediniz..'
    elsif pass.to_s.length != 6
      'Şifreniz hatalı. Kontrol ediniz..'
    elsif MailList.rey_log_kontrol(tc, pass)
      'TC numaranız bulunamadı veya şifreniz hatalı. Kontrol ediniz..'
    else
      [nil, MailList.muayene_id_get(tc, pass).to_i]
    end

  end
end

app/helpers/rey_helper.rb
module ReyHelper
end

app/views/rey/mail_page.html.erb
<div id="log_panel">
  <fieldset>
    <legend>Rey Giriş Paneli</legend>
    <%= form_for :rey_login, url: rey_page_path, html: {id: 'login_panel'} do |f| %>
        <div id="mail_log_container">
          <%= f.label 'TC Numarası :' %>
          <%= f.number_field :tc, type: 'number', id: 'rey_log_tc', autocomplete: 'off' %>
          <br>
          <%= f.label 'Şifre' %>
          <%= f.password_field :pass, {id: 'rey_log_pass', autocomplete: 'off'} %>
          <br>
        </div>
        <%= f.submit('Giriş', id: 'rey_log_sub') %>
    <% end %>
  </fieldset>
</div>

<div id="mail_list">
  <table id="mail_table">
    <tr>
      <th>Hasta İsim ve Soyisim</th>
      <th>Hasta TC</th>
      <th>Muayene Tarihi</th>
      <th>Şifre</th>
    </tr>
    <% @mails.each do |item| %>
      <tr>
        <td><%= item[1].to_s + ' ' + item[2].to_s %></td>
        <td><%= item[3].to_s %></td>
        <td><%= item[6].to_s %></td>
        <td><%= item[5].to_s %></td>
      </tr>
    <% end %>
  </table>
</div>

<% javascript_include_tag 'mail_page.js' %>

app/views/rey/rey_page.html.erb
<% if @log_result %>
  <p id="log_error"><%= @log_result %></p>
<% else %>
    <p id="rey_page_hgd">
      Bu sayfa üzerinde değerlendirmenizi yaparak gönderebilirsiniz.<br>
      İlginiz için teşekkür ederiz..
    </p>
    <div id="rey">
      <%= form_for :rey_cevap, url: rey_use_url(myn_id: @muayene_id), html: {id: 'rey_form'} do |f| %>
          <table id="rey_form_table">
            <tr>
              <th>Sorular</th>
              <th>Puanlama</th>
            </tr>
            <tr>
              <td>
                <p>
                  Doktorum beni aktif bir şekilde muayene etti.
                </p>
              </td>
              <td><%= f.select :soru_1, 1..10, {prompt: 'Rey'}, id: 'puan' %></td>
            </tr>
            <tr>
              <td>
                <p>
                  Doktorum benimle konuşurken yeteri kadar göz teması
                  kurdu.
                </p>
              </td>
              <td><%= f.select :soru_2, 1..10, {prompt: 'Rey'}, id: 'puan' %></td>
            </tr>
            <tr>
              <td>
                <p>
                  Doktorum rahatsızlığıma yönelik yeterince bilgi aldı.
                </p>
              </td>
              <td><%= f.select :soru_3, 1..10, {prompt: 'Rey'}, id: 'puan' %></td>
            </tr>
            <tr>
              <td>
                <p>
                  Doktorum incitici ve rencide edici bir davranışta
                  bulunmadı.
                </p>
              </td>
              <td><%= f.select :soru_4, 1..10, {prompt: 'Rey'}, id: 'puan' %></td>
            </tr>
            <tr>
              <td>
                <p>
                  Doktorumun koyduğu teşhisi ve tedaviyi doğru buluyorum.
                </p>
              </td>
              <td><%= f.select :soru_5, 1..10, {prompt: 'Rey'}, id: 'puan' %></td>
            </tr>
            <tr>
              <td>Özel Yorum</td>
              <td><%= f.text_area :yorum, id: 'yorum' %></td>
            </tr>
          </table>

          <%= f.submit('Gönder', id: 'rey_sub') %>
      <% end %>
    </div>
<% end %>

<% javascript_include_tag 'rey_page.js' %>

app/views/rey/rey_use.html.erb
<div id="r_use">
  <p><%= @proc_response %></p>
</div>