config/routes.rb
Rails.application.routes.draw do
  # RegistrationController
  root to: 'registration#index'

  get 'registration/dr_reg_page', to: 'registration#dr_reg_page', as: :dr_reg_p

  get 'registration/hst_reg_page', to: 'registration#hst_reg_page', as: :hst_reg_p

  post 'registration/dr_reg', to: 'registration#dr_reg', as: :dr_reg

  post 'registration/hst_reg', to: 'registration#hst_reg', as: :hst_reg
  ##
  ## ReyController
  post 'rey/rey_page', to: 'rey#rey_page', as: :rey_page

  get 'rey/mail_page', to: 'rey#mail_page', as: :mail_page

  post 'rey/rey_use/:myn_id', to: 'rey#rey_use', as: :rey_use
  ##
  ## StatisticController
  post 'statistic/recalculate', to: 'statistic#recalculate', as: :recalc

  get 'statistic/data_gets', to: 'statistic#data_gets', as: :stat_page

  get 'statistic/dr_success', to: 'statistic#dr_success', as: :dr_success
  ##
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/statistic_controller.rb
class StatisticController < ApplicationController
  def recalculate
    if params[:baz_puan]
      rey = params[:baz_puan][:rey_puani]
      BazPuan.baz_puan_guncelle(rey.to_f)
    end
    if params[:recalc]
      ActiveRecord::Base.connection.execute('CALL manuel_donemlik_hesaplama()')
    end
    @act_response = {}
    @act_response[:bz_puan] = BazPuan.baz_puan_degeri
    @act_response[:donem_list] = Donem.donem_list
  end

  def data_gets
    params[:stat_opt] ? option = params[:stat_opt][:category_select] : option = nil
    @response_hash = statistic_gets(option)
  end

  def dr_success
    @doktor_basarim = {}
    @doktor_basarim[:basarim_data] = Dktr.doktor_basarim
  end

  private

  def statistic_gets(param)
    res_hsh = {}

    case param
    when 'ulke_op'
      res_hsh[:ulke] = UlkeGecmisVeri.ulke_istatistik
    when 'il_op'
      res_hsh[:il] = Il.il_istatistik
    when 'ilce_op'
      res_hsh[:ilce] = Ilce.ilce_istatistik
    when 'hastane_op'
      res_hsh[:hastane] = HastaneGecmisVeri.hastane_istatistik
    when 'dr_op'
      res_hsh[:doktor] = GecmisVeri.doktor_istatistik
    when 'hasta_op'
      res_hsh[:hasta] = HastaReyIstatistik.hasta_istatistikleri
    else
      res_hsh[:error] = true
    end

    res_hsh
  end
end

app/helpers/statistic_helper.rb
module StatisticHelper
  def il_multiple(data)
    result = []
    data.each do |item|
      result << [item[0], item[0]]
    end
    result
  end

  def ilce_multiple(data)
    result = []
    data.each_with_index do |item, index|
      result << [item[1].to_s + ', ' + item[0].to_s, index + 1]
    end
    result
  end

  def hastane_multiple(data)
    result = []
    data.each do |item|
      result << [item[1], item[0]]
    end
    result
  end

  def doktor_multiple(data)
    result = []
    data.each do |item|
      result << [item[2].to_s + ', ' + item[0].to_s + ' ' + item[1].to_s, item[2]]
    end
    result
  end

  def hasta_multiple(data)
    result = []
    data.each do |item|
      result << [item[2].to_s + ', ' + item[0].to_s + ' ' + item[1].to_s, item[2]]
    end
    result
  end
end

app/views/statistic/data_gets.html.erb
<p id="hsg" align="center">
    Görüntülemek üzere bir istatistik kategorisi seçiniz.
</p>
<div id="select_panel">
  <%= form_for :stat_opt, url: stat_page_url, method: :get, html: {id: 'main_select'} do |f| %>
      <div id="main_select">
        <ul id="category_list">
          <li>
            <%= f.radio_button :category_select, 'ulke_op', id: 'ulke_opt', checked: (true if @response_hash[:ulke]) %>
            <%= f.label 'Ülke Kayıtları', for: 'ulke_opt' %>
          </li>
          <li>
            <%= f.radio_button  :category_select, 'il_op', id: 'il_opt', checked: (true if @response_hash[:il]) %>
            <%= f.label 'İl Kayıtları', for: 'il_opt' %>
          </li>
          <li>
            <%= f.radio_button :category_select, 'ilce_op', id: 'ilce_opt', checked: (true if @response_hash[:ilce]) %>
            <%= f.label 'İlçe Kayıtları', for: 'ilce_opt' %>
          </li>
          <li>
            <%= f.radio_button :category_select, 'hastane_op', id: 'hastane_opt', checked: (true if @response_hash[:hastane]) %>
            <%= f.label 'Hastane Kayıtları', for: 'hastane_opt' %>
          </li>
          <li>
            <%= f.radio_button :category_select, 'dr_op', id: 'doktor_opt', checked: (true if @response_hash[:doktor]) %>
            <%= f.label 'Doktor Kayıtları', for: 'doktor_opt' %>
          </li>
          <li>
            <%= f.radio_button :category_select, 'hasta_op', id: 'hasta_opt', checked: (true if @response_hash[:hasta]) %>
            <%= f.label 'Hasta Kayıtları', for: 'hasta_opt' %>
          </li>
        </ul>
        <%= f.submit('Kayıtları Gör', id: 'stat_opt_sub') %>
      </div>
  <% end %>
  <div id="spec_select">
    <% if @response_hash[:il] %>
      <%= select_tag :il_list, options_for_select(il_multiple(@response_hash[:il])), {prompt: 'Tümünü Seç', id: 'il_optt', multiple: true, name: 'spec'} %>
    <% elsif @response_hash[:ilce] %>
      <%= select_tag :ilce_list, options_for_select(ilce_multiple(@response_hash[:ilce])), {prompt: 'Tümünü Seç', id: 'ilce_optt', multiple: true, name: 'spec'} %>
    <% elsif @response_hash[:hastane] %>
      <%= select_tag :hastane_list, options_for_select(hastane_multiple(@response_hash[:hastane])), {prompt: 'Tümünü Seç', id: 'hastane_optt', multiple: true, name: 'spec'} %>
    <% elsif @response_hash[:doktor] %>
      <%= select_tag :doktor_list, options_for_select(doktor_multiple(@response_hash[:doktor])), {prompt: 'Tümünü Seç', id: 'doktor_optt', multiple: true, name: 'spec'} %>
    <% elsif @response_hash[:hasta] %>
      <%= select_tag :hasta_list, options_for_select(hasta_multiple(@response_hash[:hasta])), {prompt: 'Tümünü Seç', id: 'hasta_optt', multiple: true, name: 'spec'} %>
    <% end  %>
  </div>
  <div id="unselect">
    <%= select_tag :unselect, options_for_select([]), {id: 'un_select', multiple: true} %>
  </div>
</div>
<br>
<br>
<div id="veri">
  <% if @response_hash[:il] %>
    <table id="il_veri_tablo" align="center">
      <tr>
        <th>..</th>
        <th>İl</th>
        <th>SonReyPuanı</th>
        <th>ReyPuanDeğişimi(%)</th>
        <th>OrtalamaReyPuanı</th>
        <th>Memnuniyet(%)</th>
      </tr>
      <% @response_hash[:il].each_with_index do |item, index|%>
          <tr>
            <td><%= index + 1 %># </td>
            <td id="prm_il"><%= item[0] %></td>
            <td><%= item[1].to_f %></td>
            <td><%= item[2].to_f %></td>
            <td><%= item[3].to_f %></td>
            <td><%= item[4].to_f %></td>
          </tr>
      <% end %>
    </table>
  <% elsif @response_hash[:ilce] %>
    <table id="ilce_veri_tablo" align="center">
      <tr>
        <th>..</th>
        <th>İl</th>
        <th>İlçe</th>
        <th>SonReyPuanı</th>
        <th>ReyPuanDeğişimi(%)</th>
        <th>OrtalamaReyPuanı</th>
        <th>Memnuniyet(%)</th>
      </tr>
      <% @response_hash[:ilce].each_with_index do |item, index| %>
          <tr>
            <td id="<%= index + 1 %>"><%= index + 1 %># </td>
            <td><%= item[0] %></td>
            <td><%= item[1] %></td>
            <td><%= item[2].to_f %></td>
            <td><%= item[3].to_f %></td>
            <td><%= item[4].to_f %></td>
            <td><%= item[5].to_f %></td>
          </tr>
      <% end %>
    </table>
  <% elsif @response_hash[:hastane] %>
      <table id="hastane_veri_tablo" align="center">
        <tr>
          <th>..</th>
          <th>KurumKodu</th>
          <th>Hastane</th>
          <th>HastaSayısı</th>
          <th>ReyKullanımOranı(%)</th>
          <th>ReyPuanı</th>
          <th>Memnuniyet(%)</th>
          <th>Dönem</th>
        </tr>
        <% @response_hash[:hastane].each_with_index do |item, index| %>
              <tr>
                <td><%= index + 1 %># </td>
                <td id="prm_kurum_kodu"><%= item[0].to_s %></td>
                <td><%= item[1] %></td>
                <td><%= item[4].to_i %></td>
                <td><%= item[5].to_f %></td>
                <td><%= item[6].to_f %></td>
                <td><%= item[7].to_f %></td>
                <td><%= item[2].to_s + ' / ' + item[3].to_s %></td>
              </tr>
        <% end %>
      </table>
  <% elsif @response_hash[:doktor] %>
      <table id="doktor_veri_tablo" align="center">
        <tr>
          <th>..</th>
          <th>İsim</th>
          <th>Soyisim</th>
          <th>TCNumarası</th>
          <th>HastaSayısı</th>
          <th>ReyKullanımOranı(%)</th>
          <th>ReyPuanı</th>
          <th>Memnuniyet(%)</th>
          <th>BandDeğeri</th>
          <th>Dönem</th>
        </tr>
        <% @response_hash[:doktor].each_with_index do |item, index| %>
            <tr>
              <td><%= index + 1 %># </td>
              <td><%= item[0] %></td>
              <td><%= item[1] %></td>
              <td id="prm_tc"><%= item[2].to_s %></td>
              <td><%= item[5].to_i %></td>
              <td><%= item[6].to_f %></td>
              <td><%= item[7].to_f %></td>
              <td><%= item[8].to_f %></td>
              <td><%= item[9].to_i %></td>
              <td><%= item[3].to_s + ' / ' + item[4].to_s %></td>
            </tr>
        <% end %>
      </table>
  <% elsif @response_hash[:hasta] %>
      <table id="hasta_veri_tablo" align="center">
        <tr>
          <th>..</th>
          <th>İsim</th>
          <th>Soyisim</th>
          <th>TCNumarası</th>
          <th>ToplamMuayeneSayısı</th>
          <th>ReyKullanımOranı(%)</th>
          <th>ReyPuanı</th>
          <th>Memnuniyet(%)</th>
        </tr>
        <% @response_hash[:hasta].each_with_index do |item, index| %>
            <tr>
              <td><%= index + 1 %># </td>
              <td><%= item[0] %></td>
              <td><%= item[1] %></td>
              <td id="prm_tc"><%= item[2].to_s %></td>
              <td><%= item[3].to_i %></td>
              <td><%= item[4].to_f %></td>
              <td><%= item[5].to_f %></td>
              <td><%= item[6].to_f %></td>
            </tr>
        <% end %>
      </table>
  <% elsif @response_hash[:ulke] %>
      <table id="ulke_veri_tablo" align="center">
        <tr>
          <th>..</th>
          <th>HastaSayısı</th>
          <th>ReyKullanımOranı(%)</th>
          <th>ReyPuanı</th>
          <th>Memnuniyet</th>
          <th>BazPuan</th>
          <th>Dönem</th>
        </tr>
        <% @response_hash[:ulke].each_with_index do |item, index| %>
            <tr>
              <td><%= index + 1 %># </td>
              <td><%= item[0].to_i %></td>
              <td><%= item[1].to_f %></td>
              <td><%= item[2].to_f %></td>
              <td><%= item[3].to_f %></td>
              <td><%= item[4].to_f %></td>
              <td><%= item[5].to_s + ' / ' + item[6].to_s %></td>
            </tr>
        <% end %>
      </table>
  <% end  %>
</div>

<% javascript_include_tag 'data_gets.js' %>

app/views/statistic/dr_success.html.erb
<p id="dr_hgd" >
  Sistemde kayıtlı bulunan tüm doktorların başarım verileridir.
</p>
<div id="veri_tablosu">
  <table id="dr_basarim">
    <tr>
      <th>..</th>
      <th>İsim</th>
      <th>Soyisim</th>
      <th>TCNumarası</th>
      <th>OrtalamaReyPuanı</th>
      <th>BandVerisi</th>
      <th>ReyKatılımSayısı</th>
      <th>ÇalıştığıServis</th>
      <th>ÇalıştığıKurumKodu</th>
    </tr>
    <% @doktor_basarim[:basarim_data].each_with_index do |item, index| %>
        <tr>
          <td><%= index + 1 %># </td>
          <td><%= item[0].to_s %></td>
          <td><%= item[1].to_s %></td>
          <td><%= item[2].to_s %></td>
          <td><%= item[3].to_f %></td>
          <td><%= item[4].to_i %></td>
          <td><%= item[5].to_i %></td>
          <td><%= item[6].to_s %></td>
          <td><%= item[7].to_s %></td>
        </tr>
    <% end %>
  </table>
</div>

<% javascript_include_tag 'dr_success.js' %>

app/views/statistic/recalculate.html.erb
<p id="re_hgd">
  DrRey hesaplamalarında kullanılacak olan "BazPuan" değerini buradan
  ayarlayabilirsiniz. Ancak değerin 0-100 arası olmasına dikkat ediniz.
  <br>
  Ek olarak programın ayarlanan süresinden önce dönemlik hesaplama
  yapmak istiyorsanız burada bulunan butonu kullanabilirsiniz. Aşağıdaki
  tabloda sistemde kayıtlı dönem değerlerini görebilirsiniz.
</p>
<fieldset id="baz_p">
  <div id="baz_puan">
    <%= form_for :baz_puan, url: recalc_path, html:{id: 'baz_puan_set'} do |f| %>
        <%= f.label 'Baz Puan :', for: 'baz_puan_in' %>
        <%= f.number_field :rey_puani, min: 0, max: 100, step: 0.00001, value: @act_response[:bz_puan], html: {id: 'baz_puan_in', size: 4} %>
        <%= f.submit('Ayarla', id: 'baz_puan_sub') %>
    <% end %>


    <%= button_to('DönemlikHesaplama',{controller: 'statistic', action: :recalculate, recalc: true, method: :post},
                {id: 're_calc_but'}) %>
  </div>
</fieldset>
<div id="donem_tablo">
  <table id="donem_list">
    <tr>
      <th>..</th>
      <th>Başlangıç</th>
      <th>Bitiş</th>
    </tr>
    <% @act_response[:donem_list].each do |item| %>
        <tr>
          <td><%= item[0].to_i %></td>
          <td><%= item[1].to_s %></td>
          <td><%= item[2].to_s %></td>
        </tr>
    <% end %>
  </table>
</div>
<% javascript_include_tag 'recalculate.js' %>